# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  config_env: &config
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/juice
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build:
    <<: *config

    steps:
      - checkout
      - run:
          name: Decode Configuration Files
          command: |
            echo $ENV_CONFIG | base64 --decode > ~/juice/environment.json

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Check code (styling and stuff)
          command: gradle check

      - run:
          name: Run tests
          command: gradle test

      - run:
          name: Publish to Maven
          command: gradle publish