# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  config_env: &config
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/juice
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build:
    <<: *config

    steps:
      - checkout
      - run:
          name: Decode Configuration Files
          command: |
            echo $ENV_CONFIG | base64 --decode > ~/juice/environment.json

      - run:
          name: Download dependencies
          command: ./gradlew dependencies

      - run:
          name: Check code (styling and stuff)
          command: ./gradlew check

      - run:
          name: Run tests
          command: ./gradlew test

      - run:
          name: Publish to Maven
          command: ./gradlew publish