name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check code style
      run: ./gradlew check
    - name: Test build
      run: ./gradlew test
    - name: Publish to maven
      run: ./gradlew publish
